# Generated by Django 3.1.5 on 2022-12-04 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barberies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('stars', models.FloatField()),
                ('url', models.CharField(max_length=150)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city', models.CharField(choices=[('MDE', 'Medellín')], max_length=3)),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 4, 9, 26, 43, 43771))),
            ],
        ),
        migrations.CreateModel(
            name='Barbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80, null=True)),
                ('last_name', models.CharField(max_length=80, null=True)),
                ('stars', models.FloatField()),
                ('url', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('ADM', 'Administrador'), ('IND', 'Independiente'), ('EMP', 'Empleado')], max_length=3)),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 4, 9, 26, 43, 44772))),
                ('barbery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.barberies')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('cost', models.FloatField()),
                ('span', models.TimeField()),
                ('barber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.barbers')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=2)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('barber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.barbers')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('barber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.barbers')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.services')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.users')),
            ],
        ),
    ]
